"""User,Appointment and Document

Revision ID: 8a1f2414ffb3
Revises: 
Create Date: 2026-06-24 15:54:20.974083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1f2414ffb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'FRONT_DESK', 'CLINICIAN', name='roleenums'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'WAITING', 'COMPLETED', 'CANCELLED', name='appoinmentstatus'), server_default='WAITING', nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['user_model.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('RECORD', 'INUSRANCE', name='documentype'), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appoinment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appoinment_id'], ['appointment_model.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_model')
    op.drop_table('appointment_model')
    op.drop_table('user_model')
    # ### end Alembic commands ###
